#!/usr/bin/env node

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const devDir = path.join(root, "dev");
const contentPostDir = path.join(devDir, "content", "post");
const feedUrl = process.env.FEED_URL ?? "https://asit.blog/feed.json";
const baseUrl =
  process.env.BASE_URL ??
  process.env.HUGO_BASEURL ??
  "http://localhost:1313/";
const themeConfigPath = path.join(root, "config.json");

function parseUrlParts(itemUrl) {
  const { pathname } = new URL(itemUrl);
  const match = pathname.match(/^\/(\d{4})\/(\d{2})\/(\d{2})\/(.+)\.html$/);
  if (!match) {
    throw new Error(`Unexpected post URL format: ${itemUrl}`);
  }

  const [, year, month, day, slug] = match;
  return { year, month, day, slug, pathname };
}

function clearGeneratedPosts() {
  if (!existsSync(contentPostDir)) {
    mkdirSync(contentPostDir, { recursive: true });
    return;
  }

  for (const year of readdirSync(contentPostDir)) {
    const yearPath = path.join(contentPostDir, year);
    rmSync(yearPath, { recursive: true, force: true });
  }
}

function writePost(item) {
  const { pathname, year, month, day, slug } = parseUrlParts(item.url);
  const dir = path.join(contentPostDir, year, month, day);
  mkdirSync(dir, { recursive: true });

  const frontMatter = [
    "---",
    item.title ? `title: ${JSON.stringify(item.title)}` : 'title: ""',
    `date: ${item.date_published}`,
    `url: ${pathname}`,
    "type: post",
    "draft: false",
    "---",
    "",
  ].join("\n");

  const body = item.content_html?.trim() ?? "";
  writeFileSync(path.join(dir, `${slug}.md`), `${frontMatter}${body}\n`);
}

function writeAboutPage(siteTitle) {
  const aboutDir = path.join(devDir, "content", "about");
  mkdirSync(aboutDir, { recursive: true });
  writeFileSync(
    path.join(aboutDir, "_index.md"),
    `---
title: About
---

# ${siteTitle}

Local preview page. Edit this file or export content from Micro.blog for your real about page.
`,
  );
}

function writeHugoConfig(feed, themeConfig) {
  const baseURL = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;

  const accentParams = themeConfig.params ?? {};
  const username = "asitkhanda";

  const config = `# Generated by scripts/sync-feed.mjs — do not edit by hand
baseURL = "${baseURL}"
title = ${JSON.stringify(feed.title)}
theme = ["theme-alpine", "theme-blank"]
disableKinds = ["taxonomy", "term"]
locale = "en"
defaultContentLanguage = "en"
paginate = 25
pluralizeListTitles = false
uglyURLs = false
enableRobotsTXT = false

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON", "RSD", "ArchiveHTML", "ArchiveJSON", "PhotosHTML", "PhotosJSON"]
  page = ["HTML"]
  section = ["HTML"]

[mediaTypes."application/json"]
  suffixes = ["json"]

[outputFormats.RSS]
  baseName = "feed"

[outputFormats.JSON]
  baseName = "feed"

[outputFormats.RSD]
  mediaType = "application/xml"
  baseName = "rsd"
  isPlainText = true
  notAlternative = true

[outputFormats.ArchiveHTML]
  mediaType = "text/html"
  path = "archive"
  baseName = "index"
  isHTML = true
  notAlternative = true

[outputFormats.ArchiveJSON]
  mediaType = "application/json"
  path = "archive"
  baseName = "index"
  isPlainText = true
  notAlternative = true

[outputFormats.PhotosHTML]
  mediaType = "text/html"
  path = "photos"
  baseName = "index"
  isHTML = true
  notAlternative = true

[outputFormats.PhotosJSON]
  mediaType = "application/json"
  path = "photos"
  baseName = "index"
  isPlainText = true
  notAlternative = true

[author]
  name = ${JSON.stringify(feed.title)}
  avatar = ${JSON.stringify(feed.icon)}

[params]
  theme_seconds = "0"
  paginate_home = false
  paginate_categories = false
  paginate_replies = false
  alpine_accent_text_color = ${JSON.stringify(accentParams.alpine_accent_text_color ?? "#f29c38")}
  alpine_accent_background_color = ${JSON.stringify(accentParams.alpine_accent_background_color ?? "#ffffff")}
  alpine_hover_background_color = ${JSON.stringify(accentParams.alpine_hover_background_color ?? "#fffee4")}

[params.author]
  name = ${JSON.stringify(feed.title)}
  avatar = ${JSON.stringify(feed.icon)}
  username = ${JSON.stringify(username)}

[[menu.main]]
  name = "Archive"
  url = "/archive/"
  weight = 10

[[menu.main]]
  name = "Photos"
  url = "/photos/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30
`;

  writeFileSync(path.join(devDir, "config.toml"), config);
}

async function main() {
  console.log(`Fetching ${feedUrl}...`);
  const response = await fetch(feedUrl);
  if (!response.ok) {
    throw new Error(`Failed to fetch feed: ${response.status}`);
  }

  const feed = await response.json();
  const themeConfig = existsSync(themeConfigPath)
    ? JSON.parse(readFileSync(themeConfigPath, "utf8"))
    : {};

  clearGeneratedPosts();
  for (const item of feed.items ?? []) {
    writePost(item);
  }

  writeAboutPage(feed.title);
  writeHugoConfig(feed, themeConfig);

  console.log(`Synced ${feed.items?.length ?? 0} posts to dev/content/post/`);
  console.log("Updated dev/config.toml with accent colors from config.json");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
